sudo: false
language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
#    - TOXENV=lint
install:
    - pip install -r requirements.txt
before_script:
    - TOXENV=lint tox
script:
    - tox
after_success:
    - coveralls
